# Generated by Django 3.1.7 on 2021-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20200605_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfo',
            name='Code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cinfo',
            name='PhoneNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='phoneNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Aadhar',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='Code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vinfo',
            name='PhoneNo',
            field=models.CharField(max_length=10),
        ),
    ]
